[package]
name = "gl"
version = "0.1.0"
authors = ["Agorgianitis Loukas <agorglouk@gmail.com>"]
description = "OpenGL bindings"

[dependencies]
backtrace = "0.3.9"

[build-dependencies]
gl_generator = { version = "0.9.0", features = ["unstable_generator_utils"] }
